### ISSUE TITLE
Can't find SceneGrok

### ISSUE THREAD

**Issue by yuangan** [msavva/pigraphs#5]
Hi Savva, 

I'm running your PiGraph code, but stuck in JavaApps/target/SceneGrok-0.0.1.jar.
Actually, we can't find the SceneGrok in PiGraph code. Could you give me some tips?

Thank you very much :)

**Comment by msavva** [comment]
Hi @yuangan thank you for trying out the PiGraphs codebase.

The jar file is used to provide an interface between the C++ code in PiGraphs and Java code of supporting libraries (mostly the Weka library for running ML models, and the CoreNLP library for parsing input text). 

The jar file is generated by building the java interface (see https://github.com/msavva/pigraphs#regenerating-proxy-code-for-interfacing-with-weka-using-jace).  This process is unfortunately not documented very well, and was only tested on a particular setup (IntelliJ IDEA with Maven support installed).  If you want to build it, that is the setup I would recommend.

However, you can also get a pre-built jar file from the prepared VM image and try the code there directly (see https://github.com/msavva/pigraphs#prepackaged-vm-image for instructions).

**Comment by yuangan** [comment]
Thank you very much, I'll run the prepared VM image directly.
